import { describe, expect, it } from 'vitest'
import { steering } from './steering'
import { emptyUsage } from '../core/model'
import type { Event, Session } from '../core/model'
import type { ProcessorContext } from '../core/processor'

function buildSession(turns: Array<{ text: string; sidechain?: boolean }>): Session {
  const events: Event[] = turns.map((t, i) => ({
    kind: 'user',
    text: t.text,
    blocks: [],
    isSidechain: t.sidechain ?? false,
    seq: i,
  }))
  return {
    id: 'claude-code:s',
    sessionId: 's',
    source: 'claude-code',
    provider: 'anthropic',
    project: { cwd: '/repo', repo: 'o/r' },
    models: [],
    tokens: emptyUsage(),
    events,
    toolCalls: [],
    raw: { path: '', contentHash: 'h' },
  }
}

const noopLog = { debug() {}, info() {}, warn() {}, error() {} }

function ctx(session: Session): ProcessorContext {
  return {
    session,
    log: noopLog,
    llmEnabled: false,
    llm: null,
    existingFeatures: [],
    rejectedFeatureTitles: [],
    userLinkedArtifacts: [],
    prBlockAttributions: [],
    sh: async () => null,
  }
}

function annotation(res: { annotations?: Array<{ key: string; value: unknown }> }, key: string): unknown {
  return res.annotations?.find((a) => a.key === key)?.value
}

describe('steering', () => {
  it('counts substantive follow-ups; opener and bare approvals excluded', async () => {
    const session = buildSession([
      { text: 'add a codex adapter' }, // opener — never counted
      { text: 'yes, continue' }, // bare approval — dropped
      { text: 'no, use the default sqlite db instead' }, // steering
      { text: 'lgtm' }, // bare approval — dropped
      { text: 'now commit and open a PR' }, // follow-up (progression, but deterministically countable)
    ])
    const res = await steering.run(ctx(session))
    expect(annotation(res, 'followup_count')).toBe(2)
    expect(annotation(res, 'steering')).toBe('yes')
  })

  it('a session with only an opener has no steering', async () => {
    const res = await steering.run(ctx(buildSession([{ text: 'fix the typo in README' }])))
    expect(annotation(res, 'followup_count')).toBe(0)
    expect(annotation(res, 'steering')).toBe('no')
  })

  it('ignores sidechain and synthetic pseudo-user turns', async () => {
    const session = buildSession([
      { text: 'refactor the parser' },
      { text: '<command-name>/compact</command-name>' }, // slash-command echo — synthetic
      { text: 'Caveat: The messages below were generated by the user while running local commands.' }, // synthetic
      { text: 'subagent turn', sidechain: true }, // sidechain — not the human steering this session
    ])
    const res = await steering.run(ctx(session))
    expect(annotation(res, 'followup_count')).toBe(0)
    expect(annotation(res, 'steering')).toBe('no')
  })

  it('handles a session with no user turns at all', async () => {
    const res = await steering.run(ctx(buildSession([])))
    expect(annotation(res, 'followup_count')).toBe(0)
    expect(annotation(res, 'steering')).toBe('no')
  })
})
