/**
 * Regenerate the disclosed schema reference for the tuneloop-query skill from the
 * canonical store SCHEMA (reflected out of an in-memory store), so the checked-in
 * reference can never drift from `SCHEMA_VERSION`. Run: `npm run gen:query-skill`.
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { canonicalSchema } from '../src/query/run'

const OUT = fileURLToPath(new URL('../skills/tuneloop-query/reference/schema.md', import.meta.url))

const dump = canonicalSchema()
const out: string[] = [
  '<!-- generated by `npm run gen:query-skill` — do not edit by hand -->',
  '',
  `# Schema reference (store v${dump.schemaVersion ?? '?'})`,
  '',
  'The live `tuneloop query --schema` is authoritative; this is a checked-in copy,',
  'regenerated from the store schema so it stays in sync.',
  '',
  '## Tables',
  '',
  '```sql',
]
for (const t of dump.tables) out.push(`${t.sql.trim()};`, '')
out.push('```', '', '## Facets (chartable/filterable dimensions)', '')
for (const f of dump.facets) {
  const col = f.column && f.column !== f.key ? ` → \`${f.column}\`` : ''
  const base = f.base ? `, base \`${f.base}\`` : ''
  out.push(`- \`${f.key}\` — ${f.type}, ${f.source} grain${col}${base}`)
}
out.push('', '## Measures (aggregations)', '')
for (const m of dump.measures) out.push(`- \`${m.key}\` — ${m.agg}(\`${m.expr}\`) at ${m.source} grain`)
out.push('')

writeFileSync(OUT, out.join('\n'))
process.stdout.write(`wrote ${OUT}\n`)
